In [1]:
from SOAI.handler.SOAIDiskHandler import SOAIDiskHandler
from SOAI.handler.SOAIDBHandler import SOAIDBHandler
from SOAI.sensors.SOAISensorNetwork import SOAISensorNetwork

import os

INFO - __init__ : <module>() - Use /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/.. as project path.
WARNING - __init__ : <module>() - SOAI_MODEL_PATH not set
INFO - __init__ : <module>() - SOAI env var is set to /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/..
DEBUG - __init__ : wrapper() - $HOME=/home/nils
DEBUG - __init__ : wrapper() - CONFIGDIR=/home/nils/.config/matplotlib
DEBUG - __init__ : wrapper() - matplotlib data path: /home/nils/workspace/school_of_ai/projects/air-quality-backend/env/air/lib/python3.7/site-packages/matplotlib/mpl-data
DEBUG - __init__ : rc_params_from_file() - loaded rc file /home/nils/workspace/school_of_ai/projects/air-quality-backend/env/air/lib/python3.7/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG - __init__ : <module>() - matplotlib version 3.1.2
DEBUG - __init__ : <module>() - interactive is False
DEBUG - __init__ : <module>() - platform is linux
DEBUG - __init__ : <module>() - loaded modules: ['sys

DEBUG - __init__ : wrapper() - CACHEDIR=/home/nils/.cache/matplotlib
DEBUG - font_manager : <module>() - Using fontManager instance from /home/nils/.cache/matplotlib/fontlist-v310.json


### Load data (e.g. disk)

In [2]:
diskHandler = SOAIDiskHandler()
  
dfOpenAir = diskHandler.fGetOpenAir(os.environ.get("SOAI") + "/data/openair/", selectValidData=True) # Measurments
dfOpenAirSensors = diskHandler.fGetOpenAirSensors() # Locations of the sensors
  
dfLanuv = diskHandler.fGetLanuv(os.environ.get("SOAI") + "/data/lanuv/") # Measurments
dfLanuvSensors = diskHandler.fGetLanuvSensors() # Locations of the sensors

dfTraffic = diskHandler.fGetTrafficData(os.environ.get("SOAI") + "/data/traffic/")

DEBUG - SOAIDiskHandler : fGetOpenAir() - Load OpenAir Cologne data from /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/.
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/df_openair6.parquet
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/df_openair2.parquet
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/df_openair4.parquet
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/df_openair3.parquet
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../data/openair/df_openair5.parquet
DEBUG - SOAIDiskHandler : fGetOpenAir() - 	- Load /home/nils/workspace/

# Calibrate

### Start sensor network

In [3]:
# The config file exhibits all information about active sensors, the calibration model etc.
network = SOAISensorNetwork(os.environ.get("SOAI") + "/configs/sensorNetwork.conf")

# Check the sensor network for consistency
network.fCheckNetwork()

# Setup traffic models
network.fSetUpTrafficModels(os.environ.get("SOAI") + "/configs/sensorTraffic.conf")

DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f741c at location (50.9809, 6.7851)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f741c at location (50.9809, 6.7851)
WARNING - SOAIOpenAirSensor : fLoadCalibration() - No calibration model found in path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f741c.h5. Set sensor as inactive.
DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f16fc at location (50.9602, 6.9573)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f16fc at location (50.9602, 6.9573)
DEBUG - SOAIOpenAirCalibrationModel : fLoad() - Load model from path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f16fc.h5
DEBUG - SOAIOpenAirSensor : __init__() - Set up Op

/home/nils/workspace/school_of_ai/projects/air-quality-backend/env/air/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/nils/workspace/school_of_ai/projects/air-quality-backend/env/air/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.21.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f6b16 at location (50.8939, 6.9639)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f6b16 at location (50.8939, 6.9639)
DEBUG - SOAIOpenAirCalibrationModel : fLoad() - Load model from path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f6b16.h5
DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f4474 at location (50.9601, 6.9216)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f4474 at location (50.9601, 6.9216)
DEBUG - SOAIOpenAirCalibrationModel : fLoad() - Load model from path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f4474.h5
DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f6774 at l

WARNING - SOAIOpenAirSensor : fLoadCalibration() - No calibration model found in path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f5112.h5. Set sensor as inactive.
DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f0fb8 at location (50.9665, 6.955)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f0fb8 at location (50.9665, 6.955)
WARNING - SOAIOpenAirSensor : fLoadCalibration() - No calibration model found in path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/calibrations/v20191221/807f0fb8.h5. Set sensor as inactive.
DEBUG - SOAIOpenAirSensor : __init__() - Set up OpenAir Cologne Sensor with ID 807f7b56 at location (50.9544, 6.9194)
DEBUG - SOAIOpenAirSensor : fLoadCalibration() - Set up calibration model for OpenAir Cologne sensior with ID 807f7b56 at location (50.9544, 6.9194)
DEBUG - SO

DEBUG - SOAILanuvSensor : __init__() - Set up Lanuv sensor with ID CHOR at location (51.019338, 6.884571)
DEBUG - SOAILanuvSensor : __init__() - Set up Lanuv sensor with ID VKTU at location (50.947268, 6.957649)
DEBUG - SOAILanuvSensor : __init__() - Set up Lanuv sensor with ID RODE at location (50.889871, 6.985074)
DEBUG - SOAILanuvSensor : __init__() - Set up Lanuv sensor with ID VKCL at location (50.962838, 7.004605)
INFO - SOAISensorNetwork : fCheckNetwork() - Status of OpenAirCologne sensors:
	26 of 37 are active.
	0 of these have an error.
INFO - SOAISensorNetwork : fCheckNetwork() - Status of Lanuv sensors:
	4 of 4 are active.
	0 of these have an error.
DEBUG - SOAILanuvSensor : fLoadTrafficModel() - Set up calibration model for OpenAir Cologne sensior with ID VKCL at location (50.962838, 7.004605)
DEBUG - SOAITrafficModel : fLoad() - Load model from path /home/nils/workspace/school_of_ai/projects/air-quality-backend/SOAI/../savedModels/traffic/v20200426/VKCL.h5


### Convert measurments to NO2

In [4]:
data = network.fDataToNO2(dfOpenAir, "OpenAirCologne")

hum            61.72
pm10               0
pm25               0
r1               198
r2              1479
rssi             -59
temp            16.1
sensorID    807f3b50
Name: 2018-08-14 08:00:00+00:00, dtype: object
hum            [61.72]
pm10             [0.0]
pm25             [0.0]
r1             [198.0]
r2            [1479.0]
rssi           [-59.0]
temp            [16.1]
sensorID    [807f3b50]
Name: 2018-08-14 08:00:00+00:00, dtype: object
[[  61.72]
 [  16.1 ]
 [1479.  ]]
[[  61.72]
 [  16.1 ]
 [1479.  ]]


ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,3)

In [10]:
import numpy as np
#dataDict = {"rgreen": [0.1, 0.2], "rorange": [0.1, 0.2], "rred": [0.3, 0.4], "rbrown": [0.5, 0.6], "hum": [0.1, 0.2], "temp": [0.1, 0.2], "wg": [0.1, 0.2]}
dataDict = {"no2": 40, "rgreen": 0.1, "rorange": 0.1, "rred": 0.3, "rbrown": 0.5, "hum": 0.1, "temp": 0.1, "wg": 0.1}

In [9]:
#data = np.array([dataDict["rgreen"], dataDict["rorange"], dataDict["rred"], dataDict["rbrown"], dataDict["hum"], dataDict["temp"],   dataDict["wg"]])
#print(data)
#data = data.reshape(1, -1)
#print(data)

[0.1 0.1 0.3 0.5 0.1 0.1 0.1]
[[0.1 0.1 0.3 0.5 0.1 0.1 0.1]]


In [12]:
network.fFindSensorFromID("Lanuv", "VKCL").fDataToTraffic(dataDict)

array([[77.56888]], dtype=float32)